services:
  send.localhost:
    hostname: send.localhost
    build:
      context: ./send
    ports:
      - "8080:25"
  recv.localhost:
    hostname: recv.localhost
    build:
      context: ./recv
    command: postfix start-fg
