services:
  mta.localhost:
    hostname: mta.localhost
    build:
      context: ./mta
    command: /bin/sh -c "while :; do sleep 10; done"
  mda.localhost:
    hostname: mda.localhost
    build:
      context: ./mda
    command: postfix start-fg
